[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid

[program:api]
command=python /opt/program/api_service.py
directory=/opt/program
autostart=true
autorestart=true
startretries=5
startsecs=5
stderr_logfile=/var/log/supervisor/api-err.log
stderr_logfile_maxbytes=10MB
stdout_logfile=/var/log/supervisor/api-out.log
stdout_logfile_maxbytes=10MB 